name: CICD

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: mvn package
      run: |
        cd Blog-Cloud-Backend/Eureka-Server
        mvn package
        cd ..
        
        cd Auth-Service
        mvn package
        cd ..
        
        cd Comment-Service
        mvn package
        cd ..
        
        cd Favo-Service
        mvn package
        cd ..
        
        cd User-Service
        mvn package
        cd ..
        
        cd Blog-Service
        mvn package
        cd ..
        
    - name: run eureka
      run: |
        nohup java -jar Blog-Cloud-Backend/Eureka-Server/target/Eureka-Server-0.0.1-SNAPSHOT.jar > eureka.log 2>&1 &
        
    - name: run services
      run: |
        nohup java -jar Blog-Cloud-Backend/Auth-Service/target/Auth-Service-0.0.1-SNAPSHOT.jar > Auth.log 2>&1 &
        nohup java -jar Blog-Cloud-Backend/Comment-Service/target/Comment-Service-0.0.1-SNAPSHOT.jar > Comment.log 2>&1 &
        nohup java -jar Blog-Cloud-Backend/Favo-Service/target/Favo-Service-0.0.1-SNAPSHOT.jar > Favo.log 2>&1 &
        nohup java -jar Blog-Cloud-Backend/User-Service/target/User-Service-0.0.1-SNAPSHOT.jar > User.log 2>&1 &
        nohup java -jar Blog-Cloud-Backend/Blog-Service/target/Blog-Service-0.0.1-SNAPSHOT.jar > Blog.log 2>&1 &
        
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: run tests
      run: |
        cd Blog-Cloud-Backend/Auth-Service
        mvn test
        cd ..
        
        cd Comment-Service
        mvn test
        cd ..
        
        cd Favo-Service
        mvn test
        cd ..
        
        cd User-Service
        mvn test
        cd ..
        
        cd Blog-Service
        mvn test
        cd ..

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy operation
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf Blog-Cloud.tar ../build/

    - name: upload file by ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "Blog-Cloud.tar"
        target: "/home/ubuntu/code"
