pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                script {
                    def modules = ['Auth-Service', 'Blog-Service', 'Comment-Service', 'Eureka-Server', 'Favo-Service', 'User-Service']

                    for (def module in modules) {
                        dir(module) {
                            sh 'mvn -B -DskipTests clean package'
                        }
                    }
                }
            }
        }
    }
}
